# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mon_interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.InputLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.InputLineEdit.setObjectName("InputLineEdit")
        self.gridLayout.addWidget(self.InputLineEdit, 1, 0, 1, 1)
        self.ValidationBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ValidationBtn.setObjectName("ValidationBtn")
        self.gridLayout.addWidget(self.ValidationBtn, 1, 1, 1, 1)
        self.ConsoleLbl = QtWidgets.QLabel(self.centralwidget)
        self.ConsoleLbl.setObjectName("ConsoleLbl")
        self.gridLayout.addWidget(self.ConsoleLbl, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ValidationBtn.setText(_translate("MainWindow", "Validé"))
        self.ConsoleLbl.setText(_translate("MainWindow", "..."))
